services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  GeorgRinger\Invero\:
    resource: '../Classes/*'

  GeorgRinger\Invero\Configuration:
    public: true

  GeorgRinger\Invero\Backend\RecordGroup:
    public: true

  GeorgRinger\Invero\EventListener\LocalizePageTree:
    tags:
      - name: event.listener
        event: TYPO3\CMS\Backend\Controller\Event\AfterPageTreeItemsPreparedEvent

  GeorgRinger\Invero\EventListener\ModifyRecordListTableActionsEventListener:
    tags:
      - name: event.listener
        event: TYPO3\CMS\Backend\RecordList\Event\ModifyRecordListTableActionsEvent
